### ISSUE TITLE
Different actions for different states

### ISSUE THREAD

**Issue by ads1230** [kormax/apple-home-key-reader#10]
Hi, I'm struggling a bit to get this to work
I want to make it so if locked it performs one action and if unlocked another.
My current code is below
I would appreciate help if anyone could.

```python
    def on_endpoint_authenticated(self, endpoint):
        self._lock_target_state = 0 if self._lock_current_state else 1
        log.info(
            f"Toggling lock state due to endpoint authentication event {self._lock_target_state} -> {self._lock_current_state} {endpoint}"
        )
        self.lock_target_state.set_value(self._lock_target_state, should_notify=True)
        self._lock_current_state = self._lock_target_state
        self.lock_current_state.set_value(self._lock_current_state, should_notify=True)
        if self._lock_current_state == 0:
            requests.post("http://....")
        if self._lock_current_state == 1:
            requests.post("http://....")
```

**Comment by kormax** [comment]
I mean, the decision logic looks correct, as for a payload format and request type, that depends on what solution you're trying on hooking up to, and what API it uses.

I'm gonna keep this thread open in case someone can provide a real example for something like HomeAssistant.

**Comment by ads1230** [comment]
> I mean, the decision logic looks correct, as for a payload format and request type, that depends on what solution you're trying on hooking up to, and what API it uses.
> 
> I'm gonna keep this thread open in case someone can provide a real example for something like Home Assistant.

Thanks, it's a HA web hook.
The web hooks work fine if not in the conditional statements, but when in the statement fail.

**Comment by ads1230** [comment]
Ok worked it out. During testing I was using the home app to lock unlock.
Seems to work well when tapped.
