### ISSUE TITLE
lock status info after restart

### ISSUE THREAD

**Issue by kuroio** [kormax/apple-home-key-reader#15]
Hi first of all congratulations for the project, it works great, my question is when the program is interrupted obviously on HomeKit the lock goes to no response, and this is normal, the problem arises when the program is restarted because the lock status goes to unlocked , in this way having done an automation with my real lock (Nuki) the automation opens the door for me and this is a problem, can the NFC lock start on closed when the program starts? Thank you for the time you dedicate to the project

**Comment by kormax** [comment]
I'm gonna add a "default state" option. With "locked" being default.

**Comment by kuroio** [comment]
thanks that would be perfect

**Comment by kormax** [comment]
4245459 adds the requested configuration capability

**Comment by kuroio** [comment]
thank you very much I will install it soon

**Comment by kuroio** [comment]
Hi Kormax, I tried the fixes, now the lock starts from a closed state after restarting the program, thank you so much for helping me, bye
