### ISSUE TITLE
Only Read Kreditcard

### ISSUE THREAD

**Issue by peck-lack** [kormax/apple-home-key-reader#19]
For Some Reason I can't explain every time I try to you the express Mode by Holding my Phone and Front of the NFC Reader try to use my Kreditcard. I don't know if it do that cause of it not fully Authentic auf der HomeKit System.

https://github.com/kormax/apple-home-key-reader/assets/62207956/8d023174-dff4-4659-be34-4c17d4282d07

**Comment by kormax** [comment]
Very strange.

Credit card appears if it detects a field, but for some reason there's no ECP frame indicating that it's a Home Key reader. Apple just assumes that if it's not something special - then it's payment. 

The credit card isn't actually read until you authenticate, but that's a whole other problem.

Here are my guesses on what could be wrong:

1) Poor NFC antenna could have issues sending ECP frame. If your phone works but watch doesn't - a big chance of that.

2) Device wasn't added into HomeKit, which causes no proper ECP frame to be sent.

3) Other program on the device attempts to control NFC and breaks ECP pollingloop.

4) You disabled ECP in configuration.


Could something from that list ring a bell?

**Comment by peck-lack** [comment]
1. Am Curly using the Same NFC Reader, that has bin used in the Project.
2. In My Eyes it has bin fully Setup and Integrated in HomeKit but see vor your self.
3. there ist Only This Single Connection between the Programming the NFC Reader 
4.  I fully checkt that i didn't turned it of by accident

But for the Watch I just showed it with it so I can use my phone to Record it. But Its the same on the watch and on the phone.

also I wondert were the information is hidden, were stuff like manufacture ID, Modell number and serial number could stand. so I can try to implement the QR/NFC HomeKit code.

![IMG_2934](https://github.com/kormax/apple-home-key-reader/assets/62207956/bc8226a7-a084-4202-ac71-74037fc687c5)

**Comment by kormax** [comment]
I believe you on 4) and 2). So we can keep that at rest. That leaves:


1) Regarding 1:

Those red NFC chips have very random quality. Your particular chip looks good visually and it's the same model, but it's hard to know if it 100% geniune.


3) Regarding 3:

You've never installed other NFC stuff on your computer, like libnfc, pcsc, and etc, right?



What could help me further either diagnosing this issue:

1) Do logs look OK, no errors?

2) If you select key manually, does it read successfully?

**Comment by peck-lack** [comment]
1. : Which file contains the logs?
2.  When I manually use the Home key, it functions properly.

**Comment by kuroio** [comment]
the same thing happened to me too with a low quality nfc chip, as soon as I replaced it the problem was solved

**Comment by kormax** [comment]
You have an old version of the project. Please pull/download the new one and write back.

**Comment by peck-lack** [comment]
Actually, this was my first time doing it, so I don't have any old data or previous versions.
As soon as I get off the train, I'll give it a try.

**Comment by peck-lack** [comment]
now I got this log/error  message:
Traceback (most recent call last):
  File "/Users/marlonkuhlmann/Homekey/repository.py", line 30, in _load_state_from_file
    configuration = json.load(open(self.storage_file_path, "r+"))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'homekey.json'
[2024-02-20 19:32:45,466] [    INFO] accessory_driver  :483  Loading Accessory state from `hap.state`
[2024-02-20 19:32:45,467] [   ERROR] service           :175  Connecting to the NFC reader...
NoneType: None
[2024-02-20 19:32:45,467] [    INFO] accessory_driver  :320  Starting the event loop
[2024-02-20 19:32:45,467] [    INFO] __init__          :148  searching for reader on path tty:usbserial-110:pn532
[2024-02-20 19:32:45,468] [    INFO] accessory_driver  :372  Starting accessory NFC Lock on addresses ['192.0.0.2'], port 51926.
To use the QR Code feature, use 'pip install HAP-python[QRCode]'
Enter this code in your HomeKit app on your iOS device: 464-20-687
[2024-02-20 19:32:45,699] [    INFO] __init__          :151  using PN532v1.6 at /dev/cu.usbserial-110

**Comment by kormax** [comment]
Looks fine. Add the new device into your apple home again. And try making an NFC auth.

If it fails - then send me another sample.

**Comment by peck-lack** [comment]
ok I did and it and the log is the same but its stuck on seeing up the door lock in HomeKit

**Comment by peck-lack** [comment]
I finally found out why it doesn't work. I have to power it with 5V, not 3.3V, and my USB-to-UART adapter only outputs 3.3V. So, I hooked it up to an extreme power supply, and it worked.

https://github.com/kormax/apple-home-key-reader/assets/62207956/123d9c6f-280a-441e-b096-e9c1606cb45d

**Comment by kormax** [comment]
Good to know.

Thanks for reporting back!

**Comment by peck-lack** [comment]
I have one more point to discuss. For my project, I need to specify details such as the manufacturer's name. Additionally, I have prepared a HomeKit QR code that I intend to use consistently throughout the project. I'm wondering where I can input this information. Specifically, where can I register details like the model number, manufacturer's name, etc.?

**Comment by kormax** [comment]
IDK how to do that. For that info, refer to HAP-Python repository.
