### ISSUE TITLE
discussion: esp32 firmware?

### ISSUE THREAD

**Issue by aescolastico** [kormax/apple-home-key-reader#27]
anyone reckon if this implementation is lightweight enough to be turned into custom firmware for esp32 devices?

**Comment by kormax** [comment]
It has already been done. 

You can look into the projects I've started, there's one doing just that.

**Comment by aescolastico** [comment]
> It has already been done.
> 
> You can look into the projects I've started, there's one doing just that.

ah cool. mind pointing me to the repo/path? i only see a fork of esphome, but not sure what that would have to do with diying homekey specifically?

**Comment by kormax** [comment]
https://github.com/rednblkx/HK-HomeKit-Lib
