### ISSUE TITLE
Sharing key to apple watch

### ISSUE THREAD

**Issue by mteras** [kormax/apple-home-key-reader#30]
I installed the newest version on a RPi 3 with the pn532. Everything works great on my iPhone 13 pro max. 
When I try to share the key to my apple watch series 7 from the watch app "Wallet & Apple pay" I get the following error: "Could Not Add Key - Try again later. If the problem continues, the locks might have to be removed and added again in the Home app."

Am I doing something wrong or is this just apple trying to discourage diy stuff?

**Comment by kormax** [comment]
To me it looks like you've hit the limit of available cards on Apple Watch, which is 16.

If that's rhetorical case, just remove one-two credit cards from it.

If the issue persists, try adding virtual lock to the second home instance and check if a key is provisioned in that case.

**Comment by mteras** [comment]
Thank you for the quick reply.
I tried removing a couple of credit cards from the watch, I had 5. That didn't help.
Not sure I understood the latter correctly, I tried creating a second home, adding the virtual lock to that and the same error persisted.

**Comment by kormax** [comment]
In that case, I don't know what to suggest.

Key enrollment is a process performed by system HomeKit and SE services, triggered by a lock added into a home, but the lock itself does not take part in the enrollment process.

So the issue is with one of the following:
- User account;
- Device (perhaps a factory reset could help);
- Home installation.

**Comment by kormax** [comment]
Oh, and BTW. Normally you don't need to share the key manually, as the OS attempts adding it to your secondary devices automatically.

This makes me thing that there's something wrong.
