### ISSUE TITLE
Multiple Devices

### ISSUE THREAD

**Issue by ImNoahDev** [kormax/apple-home-key-reader#33]
Hi,
Is it possible to pair multiple devices so that I do not have to buy a HomeKit hub to share the homekey?
Thanks

**Comment by kormax** [comment]
Sadly, with new HomeKit architecture there's no way.

**Comment by ImNoahDev** [comment]
Is it possible to run multiple instances of the homekey reader on the same device then?

**Comment by kormax** [comment]
You can with some code changes, but it's the home owner device who decides what the reader id and private keys are going to be, which could cause problems as early as at ECP stage, where your device decides if it wants to trigger express mode based on seeing a known reader identifier inside of ECP frame.

If that's not a problem, I can see a reader theoretically switching between virtual "subprofiles" when failing to authenticate device until it finds a profile that matches to that particular device.

If you want to try it out - you can attempt to. But I cannot give a 100% assurance that it will work.
