### ISSUE TITLE
Installing requirements.txt 

### ISSUE THREAD

**Issue by Maxtaiani** [kormax/apple-home-key-reader#38]
Hi There,

I'm trying to grasp the installation procedure. I’m using a Linux (Ubuntu) environment with Python 3.9

When I run the following “python3 -m pip install -r requirements.txt” I get a return showing it cannot locate a file in the directory. 

Can someone advise where the txt file needs to go I’ve tried placing in all different parts on the venv directory with not much luck.

Thanks !

**Comment by Maxtaiani** [comment]
Hi Kormax,

Managed to sort it thankyou!

I have managed to add the key to the apple wallet. I'm not sure if this has been asked in any of the previous discussions but when the Phone is presented to a card reader I am getting a cycle of different numbers. Is it possible to set this as static and if so im assuming within a config folder somewhere?

I have attached an image from my access control system showing the Card number/UUID not being static.

Thanks a lot
![image](https://github.com/user-attachments/assets/fd301731-062d-41db-818b-b83f9a51937e)

**Comment by neoaurion** [comment]
Hi, Sorry for the basic question but how do you create the home key in the wallet without any other door locker ? Thank you.

**Comment by kormax** [comment]
You don't. It's impossible.

**Comment by kormax** [comment]
> I am getting a cycle of different numbers.

You are getting a cycle of different numbers because it works as intended. You have to use HomeKey with a reader that supports it by implementing the underlying protocol. UID is randomized to prevent tracking by readers that do not implement the protocol.

**Comment by neoaurion** [comment]
> > Hi, Sorry for the basic question but how do you create the home key in the wallet without any other door locker ? Thank you.
> 
> You don't. It's not possible.
> 
> Card is generated by the OS when it sees that you have a compatible lock in your Home app. You cannot generate a card on your own.
> 
> We don't have any control over any property of the card apart from its color, which is actually the color of the lock, the OS uses it to pick a color for the image when generating a card.

Thank you, does this project appears as a official HomeKit locker ?

**Comment by kormax** [comment]
> Thank you, does this project appears as an official HomeKit lock?

Yes, yes it does.
