### ISSUE TITLE
Add support for UWB unlocking

### ISSUE THREAD

**Issue by DJAMIRSAM** [kormax/apple-home-key-reader#39]
Not sure if this is the place to put this but I was wondering if there is any plans to enable the usage of UWB to unlock the door as Apple added that to the standard in June.

**Comment by DJAMIRSAM** [comment]
Ah that's unfortunate, off topic but does this mean that if UniFi implemented this it would add native Access NFC card?

**Comment by kormax** [comment]
I don’t think that UniFi will be allowed to implement Aliro-based HomeKey, as Apple restricts the use of HomeKey only for readers which are personal home use only (UniFi access is aimed at businesses).

Aliro-based access badges - that might as well happen. In fact, I know that UniFi is investigating this solution. But beware, that Apple charges recurring licensing fees (some amount of $ per user per month/year) for an ability to issue access badges, so native access cards, when they happen, will surely be available to premium users only.
