### ISSUE TITLE
Raspberry Pi Zero 2 W problems need help !

### ISSUE THREAD

**Issue by RedJohn14** [kormax/apple-home-key-reader#40]
I am using a Raspberry Pi Zero 2 W and currently don’t have an FTDI adapter. Is it necessary or mandatory for UART communication?

I am using GPIO 15 and GPIO 14 (TXD and RXD) for UART communication. A few days ago, everything was working fine, but now I keep getting errors like:

```
Traceback (most recent call last):
  File "/opt/apple-home-key-reader/util/threads.py", line 18, in function_
    target(*args, **kwargs)
  File "/opt/apple-home-key-reader/service.py", line 178, in run
    self.clf.open(self.clf.path)
  File "/usr/local/lib/python3.11/dist-packages/nfc/clf/__init__.py", line 149, in open
    self.device = device.connect(path)
                  ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/nfc/clf/device.py", line 112, in connect
    device = driver.init(tty)
             ^^^^^^^^^^^^^^^^
  File "", line 78, in init
  File "/usr/local/lib/python3.11/dist-packages/nfc/clf/pn532.py", line 190, in __init__
    super(Device, self).__init__(chipset, logger)
  File "/usr/local/lib/python3.11/dist-packages/nfc/clf/pn53x.py", line 478, in __init__
    chipset_communication = self.chipset.diagnose('line')
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/nfc/clf/pn53x.py", line 269, in diagnose
    return self.command(0x00, data, timeout=1.0) == data
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/nfc/clf/pn53x.py", line 211, in command
    raise IOError(errno.EIO, os.strerror(errno.EIO))
OSError: [Errno 5] Input/output error
```
I have already tried both ttyAMA0 and ttyS0, but neither works. I have also configured the serial settings on the Raspberry Pi correctly.

And I also get this erros.

```
[2024-09-21 22:27:37,300] [   ERROR] service           :175  Connecting to the NFC reader...
NoneType: None
[2024-09-21 22:27:37,301] [    INFO] __init__          :148  searching for reader on path tty:ttyAMA0:pn532
[2024-09-21 22:27:38,379] [   ERROR] pn53x             :210  frame lenght value mismatch
[2024-09-21 22:27:38,380] [   ERROR] threads           :20   Unhandled exception in runner homekey. Continuing in 5 seconds
Traceback (most recent call last):
```

**Comment by kormax** [comment]
Try removing the `tty` prefix from AMA0

**Comment by RedJohn14** [comment]
> Try removing the `tty` prefix from AMA0

Thank for this tip. I have tested AMA0 and S0 (ttyS0). Nothing worked :-(. Any ideas why? If I used some FTDI adapter on a Raspberry PI4 it will work. But I want to use the zero pi without FTDI adapater.

**Comment by kormax** [comment]
Frankly, I don't know exactly what could be the problem with your set up, so I'm gonna drop a couple of points worth checking (apart from those you did).

1. If your PN532 board is red, check that the switches are configured properly for UART.

2. Verify that you're using the proper rx tx pins matched for AMA0.

3. Don't forget that tx and rx have to be swapped between recepient and sender device.

3. [According to NFCPY example](https://nfcpy.readthedocs.io/en/latest/overview.html#id12), AMA0 should be used without the tty for RPI, so no sense in trying other variations, as this one should be good.

**Comment by RedJohn14** [comment]
> Frankly, I don't know exactly what could be the problem with your set up, so I'm gonna drop a couple of points worth checking (apart from those you did).
> 
> 1. If your PN532 board is red, check that the switches are configured properly for UART.
> 2. Verify that you're using the proper rx tx pins matched for AMA0.
> 3. Don't forget that tx and rx have to be swapped between recepient and sender device.
> 4. [According to NFCPY example](https://nfcpy.readthedocs.io/en/latest/overview.html#id12), AMA0 should be used without the tty for RPI, so no sense in trying other variations, as this one should be good.
> 
> 4 I think you said it already, but just in case I remind to check that both the bluetooth setting is disabled, and the serial is enabled without console.

Thank man for the fast reply. So here are some additional information about my setup. I have now used some raspberry pi 4 b. Because at the moment my raspberry pi zero 2 w didn't start anymore. But the raspberry pi 4 b have same wirering. See my pictures:

![1](https://github.com/user-attachments/assets/bc74dfda-c023-49dd-8c60-7c7edf446291)
![2](https://github.com/user-attachments/assets/04f998e0-35dc-484f-88ad-e9367a6ccd38)

**Comment by kormax** [comment]
The wiring looks fine.

So it's either 

A) A dead NFC board

But if it works through a USB adapter, then

B) A misconfiguration of the serial port or software

**Comment by RedJohn14** [comment]
> The wiring looks fine.
> 
> So it's either
> 
> A) A dead NFC board
> 
> But if it works through a USB adapter, then
> 
> B) A misconfiguration of the serial port or software

Okay! So here are some extra information. I have now ordered this NFC Readers:
https://www.amazon.de/dp/B0B1QB4347?ref=ppx_yo2ov_dt_b_fed_asin_title&th=1

At the moment I have this two readers here an both of them only works with the USB Adapater.
https://www.amazon.de/dp/B0CJHVBNMS?ref=ppx_yo2ov_dt_b_fed_asin_title


Raspberry Pi:

**config.txt**
```
# Uncomment some or all of these to enable the optional hardware interfaces
dtparam=i2c_arm=off
#dtparam=i2s=on
dtparam=spi=off

dtoverlay=pi3-disable-bt
dtoverlay=disable-bt
dtoverlay=uartx

[all]
enable_uart=1
dtoverlay=uartx
dtoverlay=disable-bt
```

**configuration.json** 
```
{
    "logging": {
        "level": 20
    },

    "nfc": {
        "port": "AMA0",
        "driver": "pn532",
        "broadcast": true
    },

    "hap": {
        "port": 51926,
        "persist": "hap.state",
        "default": "locked"
    },

    "homekey": {
        "persist": "homekey.json",
        "express": true,
        "finish": "silver",
        "flow": "fast"
    }
}
```

And if i run the script python3 main.cf get this errors

```
[2024-09-22 15:57:28,768] [   ERROR] repository        :42   Could not load Home Key configuration. Assuming that device is not yet configured...
Traceback (most recent call last):
  File "/opt/apple-home-key-reader/repository.py", line 30, in _load_state_from_file
    configuration = json.load(open(self.storage_file_path, "r+"))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-09-22 15:57:28,787] [    INFO] accessory_driver  :483  Loading Accessory state from `hap.state`
[2024-09-22 15:57:28,789] [    INFO] accessory_driver  :320  Starting the event loop
[2024-09-22 15:57:28,789] [   ERROR] service           :175  Connecting to the NFC reader...
NoneType: None
[2024-09-22 15:57:28,791] [    INFO] __init__          :148  searching for reader on path tty:AMA0:pn532
[2024-09-22 15:57:28,792] [    INFO] accessory_driver  :372  Starting accessory NFC Lock on addresses ['192.168.1.5'], port 51926.
[2024-09-22 15:57:28,944] [    INFO] __init__          :151  using PN532v1.6 at /dev/ttyAMA0
[2024-09-22 15:57:29,492] [ WARNING] pn53x             :188  missing ack frame
[2024-09-22 15:57:29,492] [   ERROR] pn53x             :216  frame lenght checksum error
[2024-09-22 15:57:29,492] [   ERROR] threads           :20   Unhandled exception in runner homekey. Continuing in 5 seconds
Traceback (most recent call last):
  File "/opt/apple-home-key-reader/util/threads.py", line 18, in function_
    target(*args, **kwargs)
  File "/opt/apple-home-key-reader/service.py", line 185, in run
    self._read_homekey()
  File "/opt/apple-home-key-reader/service.py", line 111, in _read_homekey
    remote_target = self.clf.sense(
                    ^^^^^^^^^^^^^^^
  File "/opt/apple-home-key-reader/util/bfclf.py", line 202, in sense
    sense_broadcast(target, options.get("broadcast", None))
  File "/opt/apple-home-key-reader/util/bfclf.py", line 163, in sense_broadcast
    _ = self.device.chipset.in_communicate_thru(broadcast, timeout=0.25)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/apple-home-key-reader/venv/lib/python3.11/site-packages/nfc/clf/pn53x.py", line 416, in in_communicate_thru
    data = self.command(0x42, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/apple-home-key-reader/venv/lib/python3.11/site-packages/nfc/clf/pn53x.py", line 217, in command
    raise IOError(errno.EIO, os.strerror(errno.EIO))
OSError: [Errno 5] Input/output error
```

Any ideas?

I have also tested the NFC Reader on some ESP32 but on this device the ESP32 didn't find the NFC Reader. 

But with USB Connector on Pi the Reader is working very strange?!

Thanks for any help now!

**Comment by kormax** [comment]
`But with USB Connector on Pi the Reader is working very strange? `

This either means that the UART pins are dead on your PI, or that you didn't turn off Bluetooth and TTY console after all.

**Comment by RedJohn14** [comment]
> `But with USB Connector on Pi the Reader is working very strange? `
> 
> Wenn es über den USB-Adapter funktioniert, liegt das Problem auf der PI-UART-Seite. Entweder bedeutet es, dass die UART-Pins auf Ihrem PI tot sind oder dass Sie Bluetooth und TTY-Konsole doch nicht ausgeschaltet haben.

Okay I have completely reinstalled the Pi4 now. And disable Bluetooth and TTY also but get this error message. Yes with some USB Adapter it will work. The strangest thing is, that this setup was working on my pi zero 2 w. But the pi zero 2 w is now dead, because no led is flashing, so i have ordered a new one. My first setup was on the pi zero 2 w without usb adapater and work perfectly.

Did you have any information about your configuration? How did you disable bluetooth and TTY?

**Comment by kormax** [comment]
I don't have Raspberry Pi on hand right now, but when I did, i enabled AMA0 UART support through both methods:

1. raspi-config: System Options -> Serial -> Login Shell **NO** -> Serial Enabled **YES**. Reboot

2. Edit config.txt file, adding `dtoverlay=disable-bt` and `enable_uart=1`z

There are many tutorials on Google and [mentions in the official docs like those](https://www.raspberrypi.com/documentation/computers/configuration.html).

**Comment by RedJohn14** [comment]
> I don't have Raspberry Pi on hand right now, but when I did, i enabled AMA0 UART support through both methods:
> 
> 1. raspi-config: System Options -> Serial -> Login Shell **NO** -> Serial Enabled **YES**. Reboot.
> 2. Edit config.txt file, adding `dtoverlay=disable-bt` and `enable_uart=1`.
> 
> There are many tutorials on Google and [mentions in the official docs like those](https://www.raspberrypi.com/documentation/computers/configuration.html).
> 
> If nothing helps, perhaps there's something wrong with one of the hardware components in your system. In which case, I'm out if ideas for now.

Okay I have did this exactly. But get this error Message. And how did you use this Script or run it? 

It looks like the Script can not access the nfc without usb Adapter but why? Other Users have also issues.

**Comment by RedJohn14** [comment]
I have ordered new raspberry and new nfc reader. But with raspberry pi 4 and raspberry pi zero 2 w and two nfc readers won't work. Other users have also problems. any ideas?

**Comment by kormax** [comment]
As I said, I'm out of ideas. 
Maybe try running with "sudo", but there were no such errors in your logs, so I don't think it will help.

Don't remember any other users having the same issue here, so nothing comes to mind.

**Comment by ober1** [comment]
I have the similar configuration and it works fine: 
-RFID Reader: PN532 NFC NXP
- RASPBERRY PI ZERO W

The connection is the following: 
![800px-PN532_NFC_NXP_UART_connection](https://github.com/user-attachments/assets/6bba4b39-9f06-4d83-b321-353b104b9c4c)

- deactivated UART debug interface:
`raspi-config`
- System Options -> Serial -> Login Shell NO -> Serial Enabled YES. Reboot.
- configuration.js
`{
    "logging": {
        "level": 20
    },

    "nfc": {
        "port": "ttyS0", 
        "driver": "pn532",
        "broadcast": true
    },

...
    }
}`
