### ISSUE TITLE
[FEATURE REQUEST] Require support for Android with NFC HCE

### ISSUE THREAD

**Issue by NiravHK** [kormax/apple-home-key-reader#41]
Hi,

I've tried your code and it works seamlessly with iOS Homekey. Your efforts are much appreciated. Excellent Job.
I'm trying to build an app on Native Android which can communicate with PN532 (through HCE) same way it works on iOS Homekey. but I do not have skillsets for Python. 

Can you help me to understand the communication algorithm and share the steps to implement on android. So, I can create an app on Native android which can communicate to PN532 with your library.

Thanks a million in advance.

**Comment by NiravHK** [comment]
Hi,

Thank you for your prompt response on this. is there any other way possible to communicate with PN532 in both platforms Android and iOS without using wallet app and direct by our own app.

is there anyway can access lock by multiple person's device.

Thanks in advance.

**Comment by kormax** [comment]
> is there any other way possible to communicate with PN532 in both platforms Android and iOS without using wallet app and direct by our own app.
- No

> is there anyway can access lock by multiple person's device.
- Yes, by adding their iCloud accounts to your Apple Home installation
