### ISSUE TITLE
User deletion

### ISSUE THREAD

**Issue by inferutsers** [kormax/apple-home-key-reader#42]
Hello, I encountered an issue with HomeKit guest users. When adding a guest with access to the nfc lock, everything works fine and the keys register in homekey.json. The problem is when I try to delete the user, because then the program doesn't wipe its credentials from homekey.json and the key still can be used to validate even though it was deleted from the home. Can you provide a fix for that? I've noticed that when the deletion happens, the program receives the accessory_driver unpair command and logs its execution, but that's it.

**Comment by kormax** [comment]
Hi,

Thanks for your report. I'm gonna take a look into it soon.

**Comment by kormax** [comment]
Hi again,

I've added immediate handling for "unpair" events into the develop branch. 

Would be glad if you could try it out and report back.

**Comment by inferutsers** [comment]
Hello, I've tested the implementation and it seems solid. Everything works as expected. Thank you!
