### ISSUE TITLE
Closing and reopening the serial port during runtime

### ISSUE THREAD

**Issue by PatcherMustermann** [kormax/apple-home-key-reader#45]
Before HomeKey, I used my own system (read tag with security feature). I would like to continue using this system in parallel to HomeKey and would therefore like to switch the comport to my software when one of these tags is recognized. To do this, however, I would need to close the comport in HomeKey during runtime and open it again after my software has been processed.

Example in the service.py:
```
    def _read_homekey(self):
        start = time.monotonic()

        remote_target = self.clf.sense(
            RemoteTarget("106A"),
            broadcast=ECP.home(
                identifier=self.repository.get_reader_group_identifier(),
                flag_2=self.express,
            ).pack(),
        )
        if remote_target is None:
            return

        target = activate(self.clf, remote_target)
        if target is None:
            return

        if not isinstance(target, ISODEPTag):
            log.info(
                f"Found non-ISODEP Tag with UID: {target.identifier.hex().upper()}"
            )
----------> Close serial port/connection
            requests.post('http...
----------> Reopen serial port/connection
            while self.clf.sense(RemoteTarget("106A")) is not None:
                log.info("Waiting for target to leave the field...")
                time.sleep(0.5)
            return
```

What would the syntax have to be to accomplish this?

Thank you very much for your support!

Greetings
Patcher

**Comment by kormax** [comment]
You can raise an exception, which will cause the code to re-initialize the connection to the CLF after some delay. In the meanwhile, you can grab access to that port in exclusive fashion from your other app, which should prevent this one from getting it back until you release it there.

**Comment by PatcherMustermann** [comment]
Okay. But how can I trigger such an exception that the ComPort is released again? Do I simply kill the HomeKey script? Just for your information, I run the whole thing under Windows 11.

**Comment by kormax** [comment]
Just do `raise Exception("Gimme port")`or something like that in the part of the code you want this app to release access to the PN532.

**Comment by PatcherMustermann** [comment]
Sorry, but I'm not really deeply versed in python. What is a `raise Exception(“Gimme port”)`? What should the command for this look like?

**Comment by kormax** [comment]
Instead of raising an exception, you can also do something like this:

```
self.clf.close()
# Do your HTTP call here
self.clf.open(self.clf.path)
```

For HTTP call, you can use `requests` library, there are tons of examples on the web on how to use it.

**Comment by PatcherMustermann** [comment]
> For HTTP call, you can use requests library, there are tons of examples on the web on how to use it.

I had already integrated that before - thanks anyway

> self.clf.close()

That was the command I needed - Works perfectly :)

Thank you very much for your help. Now I can close this topic
