### ISSUE TITLE
RFID Reader Requirements

### ISSUE THREAD

**Issue by tomkinane** [kormax/apple-home-key-reader#8]
I'm looking into upgrading my RFID reader to a bigger range to get through a door. I'm looking for the requirements of the reader so it can be compatible with Apple Home Key

**Comment by kormax** [comment]
Provided that you implement a driver - any NFC module can work with Home Key.

As for range. Beware that even under ideal conditions (reader and device have perfect antenna match, no obstacles, good power) NFC is rated for up to 10cm. 

Regardless of what you replace, it shouldn't result in insane difference. I would say you can get 2x range difference if you're replacing a bad pn532 sample with a very good one.
